version: "1.0"
info:
  model: int-scaffold
packages:
- name: RAHS_GitServerNameWithSapceProject
  gitServerName: RAHS with Space
  gitUrl: https://github.com/rahuldemocenter/RAHS_GitServerNameWithSapceProject
  gitUsername: rahuldemocenter
  gitBranch: main
